sudo: required

services:
  - docker

before_install:
  - bundle install
  - bundle exec rake build:bosh_init
  - bundle exec rake build:spruce

script:
  - cd ${TRAVIS_BUILD_DIR} && bundle exec rake
