language: ruby
rvm:
  - 2.5

before_install:
  - gem update --system
  - gem install bundler

sudo: required

services:
  - docker

before_script:
  - bundle exec rake build:all

script:
  - bundle exec rake spec:all
