sudo: required

services:
  - docker

before_install:
  - docker build -t governmentpaas/docker-terraform .
  - docker run -d governmentpaas/docker-terraform sh -c "terraform version"
  - docker ps -a

script:
  - bundle exec rake
