---
resource_types:
- name: enum
  type: docker-image
  source:
    repository: governmentpaas/enum-resource

resources:
- name: sample-enum
  type: enum
  source:
    bucket: {{bucket-name}}
    region_name: {{aws_region}}
    versioned_file: sample-enum
    valid_values: ["yes", "no"]
    default_value: "no"

jobs:
- name: sample_enum_get_job
  plan:
  - get: sample-enum
  - task: test-task
    config:
      platform: linux
      image: docker:///alpine
      inputs:
      - name: sample-enum
      run:
        path: sh
        args:
        - -e
        - -c
        - |
          cat sample-enum/value
          # do something with value

- name: sample_enum_put_job
  plan:
  - task: test-task
    config:
      platform: linux
      image: docker:///alpine
      run:
        path: sh
        args:
        - -e
        - -c
        - |
          # do something
  - put: sample-enum
    params:
      # yaml parser can be tricksy - quotes here are to prevent implicit conversion to boolean
      value: "yes"
